name: read-json-key
author: Christian González Di Antonio
description: This action reads a JSON file and returns the value of a key

inputs:
  file:
    description: File to read
    required: true
  key:
    description: key to read
    required: true

outputs:
  value:
    description: value of the key
    value: ${{ steps.read-json-key.outputs.value }}

runs:
  using: composite
  steps:
    - name: Read JSON key
      id: read-json-key
      shell: bash
      run: |
        out=$(python $GITHUB_ACTION_PATH/../read_key.py --file ${{ inputs.file }} --key ${{ inputs.key }})

        echo "value=$out" >> $GITHUB_OUTPUT
